#!/usr/bin/env bash
set -eu
[ "$UID" -ne 0 ] || {
	echo "This script must be run by $SUDO_USER."
	exit 1
}
hostName=$(echo "$HOSTNAME" | sed 's/-PC//')
nix run home-manager/release-23.11 -- init --switch "/home/$USER/nix-dots?submodules=1#$hostName"
sleep 3
home-manager switch --flake "/home/$USER/nix-dots?submodules=1#$hostName"
sleep 1
nix develop .#fedora
