#!/usr/bin/env bash
set -eu

[ "$UID" -ne 0 ] || {
	echo "This script must be run by $SUDO_USER."
	exit 1
}
## list all flatpaks into a txt file for quick install
# flatpak list --columns=application --app >flatpaks.txt

#rpm apps install
xargs sudo dnf install -y <~/installer/files/dnf_apps.txt
sudo flatpak remote-modify --collection-id=org.flathub.Stable flathub

#Flatpak apps online install
xargs flatpak install -y <~/installer/files/flatpaks.txt

flatpak update -y
