#!/usr/bin/env bash
set -eu

[ "$UID" -ne 0 ] || {
	echo "This script must be run by $SUDO_USER."
	exit 1
}
## list all flatpaks into a txt file for quick install
# flatpak list --columns=application --app >flatpaks.txt

#rpm apps install
sudo dnf config-manager --add-repo https://pkgs.tailscale.com/stable/fedora/tailscale.repo
sudo dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
xargs sudo dnf install -y <~/installer/files/dnf_apps.txt
sleep 2

sudo flatpak remote-modify --collection-id=org.flathub.Stable flathub

#Flatpak apps online install
xargs flatpak install -y <~/installer/files/flatpaks.txt

[[ -e "$HOME/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser" ]] || mkdir -p "$HOME/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser"
rsync -av --delete --ignore-existing "$HOME/data/brave/." "$HOME/.var/app/com.brave.Browser/config/BraveSoftware/Brave-Browser/"

# Inform the user about reboot
echo "Rebooting the system..."
sleep 2

# Reboot the system
systemctl reboot
