#!/usr/bin/env bash
set -eu

# Check if the script is not run as root
[ "$UID" -ne 0 ] || {
	echo "This script must be run by $SUDO_USER."
	exit 1
}

#### Declare rest of the subvolumes you want to create in the array.
mkdir -vp /home/"$USER"/.var/app/com.brave.Browser

SUBVOLUMES=(
	"opt"
	"nix"
	"var/cache"
	"var/crash"
	"var/tmp"
	"var/log"
	"var/spool"
	"var/www"
	"var/lib/AccountsService"
	"var/lib/gdm"
	"home/$USER/.var/app/com.brave.Browser"
)
#### Run the for loop to create the subvolumes.
#### Copy from 'for' to 'done', paste it in terminal, and hit <Enter>.
for dir in "${SUBVOLUMES[@]}"; do
	if [[ -d "/${dir}" ]]; then
		sudo mv -v "/${dir}" "/${dir}-old"
		sudo btrfs subvolume create "/${dir}"
		sudo cp -ar "/${dir}-old/." "/${dir}/"
	else
		sudo btrfs subvolume create "/${dir}"
	fi
	sudo restorecon -RF "/${dir}"
done
sleep 2
btrfs subvolume list /

cat /etc/fstab
