#!/usr/bin/env bash
set -eu

[ "$UID" -eq 0 ] || {
	echo "This script must be run as root."
	exit 1
}

SUBVOLUMES=(
	"opt"
	"nix"
	"var/cache"
	"var/crash"
	"var/tmp"
	"var/log"
	"var/spool"
	"var/www"
	"var/lib/AccountsService"
	"var/lib/gdm"
	"home/$USER/.var/app/com.brave.Browser"
)

for dir in "${SUBVOLUMES[@]}"; do
	if [[ -d "/${dir}-old" ]]; then
		sudo rm -rvf "/${dir}-old"
	fi
done

btrfs subvolume list /
cat /etc/fstab
