#!/usr/bin/env bash
set -eu

# Check if the script is run as root
[ "$UID" -eq 0 ] || {
	echo "This script must be run as root."
	exit 1
}
# Check if there are any available updates
if [[ $(dnf check-update --refresh | grep -c '^[[:alnum:]]') -gt 0 ]]; then
	# Clean dnf cache
	dnf clean all
	# Update package metadata cache
	dnf makecache
	# Perform system update
	dnf update
	# Wait for a few seconds
	sleep 3
else
	echo "No updates available"
fi

# Inform the user about reboot
echo "Rebooting the system..."
sleep 2

# Reboot the system
systemctl reboot
