#!/usr/bin/env bash
set -eu

[ "$UID" -ne 0 ] || {
	echo "This script must be run by $SUDO_USER."
	exit 1
}

echo -e "Installing snapper . . .\n"
sudo dnf install snapper python3-dnf-plugin-snapper -y

sudo snapper -c root create-config /
sudo snapper -c home create-config /home

sudo snapper list-configs

sudo snapper -c root set-config ALLOW_USERS="$USER" SYNC_ACL=yes
sudo snapper -c home set-config ALLOW_USERS="$USER" SYNC_ACL=yes

ROOT_UUID="$(lsblk -f | grep FEDORA | sed 's/ \+/ /g' | cut -d ' ' -f 4)"
OPTIONS="compress=lzo"

SUBVOLUMES=(
	".snapshots"
	"home/.snapshots"
)

for dir in "${SUBVOLUMES[@]}"; do
	printf "%-41s %-35s %-5s %-s %-s\n" \
		"UUID=${ROOT_UUID}" \
		"/${dir}" \
		"btrfs" \
		"subvol=${dir},${OPTIONS}" \
		"0 0" |
		sudo tee -a /etc/fstab
done

sudo systemctl daemon-reload
sudo mount -va

sudo btrfs subvolume list /

echo 'PRUNENAMES = ".snapshots"' | tee -a /etc/updatedb.conf

# Inform the user about reboot
echo "Rebooting the system..."
sleep 2

# Reboot the system
sudo systemctl reboot
