#!/usr/bin/env bash
set -eu

[ "$UID" -eq 0 ] || {
	echo "This script must be run as root."
	exit 1
} # Need to figure out how to pkexec so we only ask for the password once.

cp -rvf ~/.themes/* /usr/share/themes/
cp -rvf ~/.icons/* /usr/share/icons/
