#!/usr/bin/env bash
set -eu

[ "$UID" -eq 0 ] || {
	echo "This script must be run as root."
	exit 1
} # Need to figure out how to pkexec so we only ask for the password once.

cp -rfL ~/.themes/. /usr/share/themes/
cp -rfL ~/.icons/. /usr/share/icons/
