#!/usr/bin/env bash
set -eu

[ "$UID" -ne 0 ] || {
	echo "This script must be run by $SUDO_USER."
	exit 1
}

SUBVOLUMES=(
	"opt"
	"nix"
	"var/cache"
	"var/crash"
	"var/tmp"
	"var/log"
	"var/spool"
	"var/www"
	"var/lib/gdm"
	"var/lib/flatpak"
	"var/lib/libvirt"
	"var/lib/AccountsService"
)
#### Run the for loop to create the subvolumes.
#### Copy from 'for' to 'done', paste it in terminal, and hit <Enter>.
for dir in "${SUBVOLUMES[@]}"; do
	if [[ -d "/${dir}" ]]; then
		sudo mv -v "/${dir}" "/${dir}-old"
		sudo btrfs subvolume create "/${dir}"
		sudo cp -ar "/${dir}-old/." "/${dir}/"
	else
		sudo btrfs subvolume create "/${dir}"
	fi
	sudo restorecon -RF "/${dir}"
done
sleep 2
sudo btrfs subvolume list /
cat /etc/fstab
